title: Zoë
subtitle: Farmer
description: Machine Learning, Modeling, & AI Engineer
email: zoe@dataleek.io
url: "https://dataleek.io"
plugins:
- jekyll-remote-theme
- jekyll-sitemap
remote_theme: andrewbanchich/forty-jekyll-theme
author: thedataleek
tiles-source: pages
tiles-count: 5
socials:
  GitHub: https://github.com/thedataleek
  LinkedIn: https://www.linkedin.com/in/zoefarmer
defaults:
  - scope:
      path: "college/notes"
    values:
      sitemap: false

kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    disable: true