title: Zoë
subtitle: Farmer
description: Machine Learning, Modeling, & AI Engineer
email: zoe@dataleek.io
url: "https://dataleek.io"
plugins:
- jekyll-sitemap
author: thedataleek
socials:
  GitHub: https://github.com/thedataleek
  LinkedIn: https://www.linkedin.com/in/zoefarmer
defaults:
  - scope:
      path: "college/notes"
    values:
      sitemap: false
  - scope:
      path: "college/presentations/d3reuse/reveal.js"
    values:
      sitemap: false
  - scope:
      path: "college/presentations/politicalboundaries/reveal.js-3.5.0"
    values:
      sitemap: false
  - scope:
      path: "college/presentations/airbnb/airbnbdashboard.html"
    values:
      sitemap: false
  - scope:
      path: "college/interpolating-3d/interpolating-3d.html"
    values:
      sitemap: false
  - scope:
      path: "assets"
    values:
      sitemap: false

kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    disable: true