title: Zoe
subtitle: Farmer
description: Data Scientist / Machine Learning Engineer
email: zoe@dataleek.io
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: andrewbanchich/forty-jekyll-theme
author: thedataleek
tiles-source: pages
tiles-count: 6
socials:
  GitHub: https://github.com/thedataleek
  LinkedIn: https://www.linkedin.com/in/zoefarmer
kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    disable: true
